spring:
  application:
    name: spring-cloud-eureka-client
  activemq:
    broker-url: tcp://localhost:61616
    broker-url-topic: tcp://localhost:61616
queue:
  stock: queue.stock
topic:
  store: topic.store
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true